
// This file has been generated by the GUI designer. Do not modify.
namespace Catalogue
{
	public partial class CataloguePreferences
	{
		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.VBox vbox2;

		private global::Gtk.CheckButton IMDb_it;

		private global::Gtk.CheckButton IMDb_univ;

		private global::Gtk.HBox hbox1;

		private global::Gtk.CheckButton Google;

		private global::Gtk.ComboBox glangbox;

		private global::Gtk.Label GtkLabel3;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Catalogue.CataloguePreferences
			this.Name = "Catalogue.CataloguePreferences";
			this.Title = global::Mono.Unix.Catalog.GetString ("Preferences for Catalogue");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child Catalogue.CataloguePreferences.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.IMDb_it = new global::Gtk.CheckButton ();
			this.IMDb_it.CanFocus = true;
			this.IMDb_it.Name = "IMDb_it";
			this.IMDb_it.Label = global::Mono.Unix.Catalog.GetString ("Create a link to IMDb (Italian version)");
			this.IMDb_it.Active = true;
			this.IMDb_it.DrawIndicator = true;
			this.IMDb_it.UseUnderline = true;
			this.vbox2.Add (this.IMDb_it);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.IMDb_it]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.IMDb_univ = new global::Gtk.CheckButton ();
			this.IMDb_univ.CanFocus = true;
			this.IMDb_univ.Name = "IMDb_univ";
			this.IMDb_univ.Label = global::Mono.Unix.Catalog.GetString ("Create a link to IMDb (Universal version)");
			this.IMDb_univ.Active = true;
			this.IMDb_univ.DrawIndicator = true;
			this.IMDb_univ.UseUnderline = true;
			this.vbox2.Add (this.IMDb_univ);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.IMDb_univ]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.Google = new global::Gtk.CheckButton ();
			this.Google.CanFocus = true;
			this.Google.Name = "Google";
			this.Google.Label = global::Mono.Unix.Catalog.GetString ("Create a link to Google");
			this.Google.Active = true;
			this.Google.DrawIndicator = true;
			this.Google.UseUnderline = true;
			this.hbox1.Add (this.Google);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Google]));
			w4.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.glangbox = global::Gtk.ComboBox.NewText ();
			this.glangbox.AppendText (global::Mono.Unix.Catalog.GetString ("Italiano"));
			this.glangbox.AppendText (global::Mono.Unix.Catalog.GetString ("English"));
			this.glangbox.AppendText (global::Mono.Unix.Catalog.GetString ("Francais"));
			this.glangbox.AppendText (global::Mono.Unix.Catalog.GetString ("Espanol"));
			this.glangbox.Name = "glangbox";
			this.glangbox.Active = 2;
			this.hbox1.Add (this.glangbox);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.glangbox]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.GtkAlignment2.Add (this.vbox2);
			this.frame1.Add (this.GtkAlignment2);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Export preferences</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel3;
			w1.Add (this.frame1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1[this.frame1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Internal child Catalogue.CataloguePreferences.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "dialog1_ActionArea";
			w10.Spacing = 10;
			w10.BorderWidth = ((uint)(5));
			w10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10[this.buttonCancel]));
			w11.Expand = false;
			w11.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-save";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10[this.buttonOk]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 393;
			this.DefaultHeight = 222;
			this.Show ();
			this.IMDb_it.Toggled += new global::System.EventHandler (this.IMDb_itToggled);
			this.IMDb_univ.Toggled += new global::System.EventHandler (this.IMDb_univToggled);
			this.Google.Toggled += new global::System.EventHandler (this.GoogleToggled);
		}
	}
}
