
// This file has been generated by the GUI designer. Do not modify.

public partial class CatalogueWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action openAction;

	private global::Gtk.Action saveAction;

	private global::Gtk.Action addAction;

	private global::Gtk.Action removeAction;

	private global::Gtk.Action aboutAction;

	private global::Gtk.Action saveAsAction;

	private global::Gtk.Action disconnectAction;

	private global::Gtk.Action convertAction;

	private global::Gtk.Action newAction;

	private global::Gtk.Action preferencesAction;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action ExitAction;

	private global::Gtk.Action EditAction;

	private global::Gtk.Action AddAction;

	private global::Gtk.Action RemoveAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action AboutAction;

	private global::Gtk.Action SaveAction;

	private global::Gtk.Action OpenAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar;

	private global::Gtk.Toolbar toolbar1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Entry entry3;

	private global::Gtk.Button SearchButton;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView mainTreeView;

	private global::Gtk.Statusbar statusbar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget CatalogueWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		w1.Add (this.openAction, "<Control><Mod2>o");
		this.saveAction = new global::Gtk.Action ("saveAction", null, null, "gtk-save");
		w1.Add (this.saveAction, null);
		this.addAction = new global::Gtk.Action ("addAction", null, null, "gtk-add");
		w1.Add (this.addAction, null);
		this.removeAction = new global::Gtk.Action ("removeAction", null, null, "gtk-remove");
		w1.Add (this.removeAction, null);
		this.aboutAction = new global::Gtk.Action ("aboutAction", null, null, "gtk-about");
		w1.Add (this.aboutAction, null);
		this.saveAsAction = new global::Gtk.Action ("saveAsAction", null, null, "gtk-save-as");
		w1.Add (this.saveAsAction, null);
		this.disconnectAction = new global::Gtk.Action ("disconnectAction", null, null, "gtk-disconnect");
		w1.Add (this.disconnectAction, null);
		this.convertAction = new global::Gtk.Action ("convertAction", null, null, "gtk-convert");
		w1.Add (this.convertAction, null);
		this.newAction = new global::Gtk.Action ("newAction", null, null, "gtk-new");
		w1.Add (this.newAction, null);
		this.preferencesAction = new global::Gtk.Action ("preferencesAction", null, null, "gtk-preferences");
		w1.Add (this.preferencesAction, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.AddAction = new global::Gtk.Action ("AddAction", global::Mono.Unix.Catalog.GetString ("Add"), null, null);
		this.AddAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add");
		w1.Add (this.AddAction, "<Control>a");
		this.RemoveAction = new global::Gtk.Action ("RemoveAction", global::Mono.Unix.Catalog.GetString ("Remove"), null, null);
		this.RemoveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Remove");
		w1.Add (this.RemoveAction, "<Control>d");
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, "<Control>h");
		this.SaveAction = new global::Gtk.Action ("SaveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, null);
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction, "<Control>s");
		this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("Open"), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction, "<Control>o");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "CatalogueWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Catalogue");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child CatalogueWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><menubar name='menubar'><menu name='FileAction' action='FileAction'><menuitem name='SaveAction' action='SaveAction'/><menuitem name='OpenAction' action='OpenAction'/><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='AddAction' action='AddAction'/><menuitem name='RemoveAction' action='RemoveAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar")));
		this.menubar.Name = "menubar";
		this.vbox1.Add (this.menubar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><toolbar name='toolbar1'><toolitem name='newAction' action='newAction'/><toolitem name='openAction' action='openAction'/><toolitem name='saveAction' action='saveAction'/><toolitem name='saveAsAction' action='saveAsAction'/><toolitem name='addAction' action='addAction'/><toolitem name='removeAction' action='removeAction'/><toolitem name='convertAction' action='convertAction'/><separator/><toolitem name='preferencesAction' action='preferencesAction'/><toolitem name='aboutAction' action='aboutAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox1.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		this.hbox1.BorderWidth = ((uint)(4));
		// Container child hbox1.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '•';
		this.hbox1.Add (this.entry3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entry3]));
		w4.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.SearchButton = new global::Gtk.Button ();
		this.SearchButton.CanFocus = true;
		this.SearchButton.Name = "SearchButton";
		this.SearchButton.UseUnderline = true;
		// Container child SearchButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w5 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w6 = new global::Gtk.HBox ();
		w6.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w7 = new global::Gtk.Image ();
		w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
		w6.Add (w7);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w9 = new global::Gtk.Label ();
		w9.LabelProp = global::Mono.Unix.Catalog.GetString ("_Find");
		w9.UseUnderline = true;
		w6.Add (w9);
		w5.Add (w6);
		this.SearchButton.Add (w5);
		this.hbox1.Add (this.SearchButton);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.SearchButton]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		this.GtkScrolledWindow.WindowPlacement = ((global::Gtk.CornerType)(3));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.mainTreeView = new global::Gtk.TreeView ();
		this.mainTreeView.CanFocus = true;
		this.mainTreeView.Name = "mainTreeView";
		this.mainTreeView.RulesHint = true;
		this.mainTreeView.SearchColumn = 1;
		this.GtkScrolledWindow.Add (this.mainTreeView);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w16.Position = 3;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar = new global::Gtk.Statusbar ();
		this.statusbar.Name = "statusbar";
		this.statusbar.Spacing = 6;
		this.vbox1.Add (this.statusbar);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar]));
		w17.Position = 4;
		w17.Expand = false;
		w17.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 648;
		this.DefaultHeight = 501;
		this.menubar.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openAction.Activated += new global::System.EventHandler (this.OpenFileButton);
		this.saveAction.Activated += new global::System.EventHandler (this.SaveFileButton);
		this.addAction.Activated += new global::System.EventHandler (this.AddLineButton);
		this.removeAction.Activated += new global::System.EventHandler (this.DeleteLineButton);
		this.aboutAction.Activated += new global::System.EventHandler (this.AboutButton);
		this.saveAsAction.Activated += new global::System.EventHandler (this.SaveFileButton);
		this.convertAction.Activated += new global::System.EventHandler (this.ExportAction);
		this.newAction.Activated += new global::System.EventHandler (this.NewActivate);
		this.preferencesAction.Activated += new global::System.EventHandler (this.PreferencesActivated);
		this.ExitAction.Activated += new global::System.EventHandler (this.ExitActivate);
		this.AddAction.Activated += new global::System.EventHandler (this.AddLineButton);
		this.RemoveAction.Activated += new global::System.EventHandler (this.DeleteLineButton);
		this.AboutAction.Activated += new global::System.EventHandler (this.AboutButton);
		this.SaveAction.Activated += new global::System.EventHandler (this.SaveFileButton);
		this.OpenAction.Activated += new global::System.EventHandler (this.OpenFileButton);
		this.SearchButton.Activated += new global::System.EventHandler (this.FindButtonActivate);
		this.SearchButton.Clicked += new global::System.EventHandler (this.FindButtonActivate);
	}
}
